### ISSUE TITLE
ConTriNet is now published and the code is released

### ISSUE THREAD

**Issue by CSer-Tang-hao** [yuanmaoxun/Awesome-RGBT-Fusion#12]
Hi,

Thank you for maintaining such a comprehensive table.

I’d like to request an update to include our recent paper titled "Divide-and-Conquer: Confluent Triple-Flow Network for RGB-T Salient Object Detection," which was accepted by TPAMI last month.

- **IEEE Xplore link**: https://ieeexplore.ieee.org/document/10778650

- **Code repository**: https://github.com/CSer-Tang-hao/ConTriNet_RGBT-SOD

Thank you for your efforts in curating this resource!

Best regards,
Howard

**Comment by yuanmaoxun** [comment]
@CSer-Tang-hao Thank you for your interest. We have update the paper in this repository.
