### ISSUE TITLE
Code open source

### ISSUE THREAD

**Issue by love-whut** [yuanmaoxun/Awesome-RGBT-Fusion#3]
Hello, will the code of your paper `Removal and Selection : Improving RGB-Infrared Object Detection via Coarse-to-Fine Fusion` be open source ?

**Comment by yuanmaoxun** [comment]
Thank you for your interest in our paper, this paper is under review and its code will be released when the paper is accepted.

**Comment by love-whut** [comment]
> Our paper:[Removal and Selection: Improving RGB-Infrared Object Detection via Coarse-to-Fine Fusion](https://arxiv.org/abs/2401.10731) has released the code at https://github.com/Zhao-Tian-yi/RSDet.git. Thank you for your interest in our paper.

Very good job!
