### ISSUE TITLE
Code Found

### ISSUE THREAD

**Issue by love-whut** [yuanmaoxun/Awesome-RGBT-Fusion#4]
The code link of `Multimodal Object Detection via Probabilistic Ensembling, ECCV2022`  is as follows:
https://github.com/Jamie725/Multimodal-Object-Detection-via-Probabilistic-Ensembling

**Comment by yuanmaoxun** [comment]
Thanks for your interest in this Repository, we will add the code link in the next commit or you can pull requests directly.
